---
# Inventário de hosts z/OS
all:
  children:
    zos_hosts:
      hosts:
        zos_system:
          ansible_host: 129.40.95.26
          ansible_user: zosadmn
          ansible_python_interpreter: /usr/lpp/IBM/cyp/v3r13/pyz/bin/python3

          # -- Autenticação: descomente UMA das opções abaixo --

          # Opção 1: certificado (chave privada)
          #ansible_ssh_private_key_file: /Users/gabriel-paiva17/Downloads/pem_user_privatekey_download.pem

          # Opção 2: senha RACF (via vault)
          ansible_ssh_pass: "{{ racf_ssh_password }}"

      vars:
        ansible_connection: ssh
        ansible_port: 22

# Made with Bob
